import type { Metadata } from "next";
import "@/app/globals.css";
import { roboto_mono } from "@/app/ui/fonts";
import Footer from "./ui/footer";
import Sidebar from "./ui/sidebar";
export const metadata: Metadata = {
  title: "Doner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className} antialiased bg-custom-dark`}>
        <div className="flex flex-row">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
