import type { Metadata } from "next";
import "@/app/globals.css";
import { roboto_mono } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className} antialiased bg-custom-dark`}>
        {children}
      </body>
    </html>
  );
}
